---
name: flutter_todo_list_online
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.2
  path: ^1.8.2
  flutter_riverpod: ^2.1.1
  test: ^1.21.4
  http: ^0.13.5
  intl: ^0.17.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
